import { ArrowLeft, CheckCircle2, FileText, ShieldCheck } from 'lucide-react';
import cpiLogo from '../../imports/image.png';
import type { AppPage } from '../App';

export const sections = [
  ['1. Objet et identité de CPI', <>Les présentes conditions régissent l’utilisation de MONESPACE.CPI, l’espace numérique de la Compagnie Prestige Immobilier (CPI SARL), société immobilière sénégalaise créée en 2003. La plateforme permet notamment de créer un compte, de renseigner un projet immobilier, de transmettre des informations et pièces justificatives, de suivre l’avancement d’un dossier et d’échanger avec les équipes CPI et, lorsque cela est nécessaire, ses partenaires autorisés.</>],
  ['2. Acceptation et capacité', <>La création d’un compte et l’utilisation de la plateforme impliquent l’acceptation des présentes conditions. L’utilisateur déclare être majeur et juridiquement capable de s’engager, ou agir avec l’autorisation de son représentant légal. Si une personne agit au nom d’une société ou d’un autre bénéficiaire, elle garantit disposer des pouvoirs nécessaires.</>],
  ['3. Compte utilisateur', <>L’utilisateur fournit des informations exactes, complètes et à jour. Il protège son mot de passe, ne partage pas son jeton ou ses identifiants et informe CPI sans délai de toute utilisation non autorisée. Un compte est personnel : il ne doit pas être créé pour usurper l’identité d’un tiers, contourner une mesure de sécurité ou créer des dossiers fictifs.</>],
  ['4. Dossier immobilier et informations transmises', <>Les informations saisies, notamment l’identité, le téléphone, la situation professionnelle, les revenus, le projet et les pièces justificatives, doivent être sincères et lisibles. L’utilisateur garantit disposer du droit de transmettre les documents déposés. Toute falsification, omission volontaire ou utilisation de documents appartenant à un tiers peut entraîner le refus ou la suspension du dossier et, le cas échéant, un signalement aux autorités compétentes.</>],
  ['5. Accompagnement, simulation et financement', <>Les simulations, estimations, orientations et messages affichés dans la plateforme sont fournis à titre indicatif, sauf contrat distinct signé par les parties. Ils ne constituent ni une promesse de prêt, ni une décision bancaire, ni une garantie d’acceptation, de taux, de montant, de délai ou de décaissement. Toute offre de financement, vente, réservation, construction, intermédiation ou prestation juridique est soumise à ses propres conditions, à la vérification du dossier et à la signature des documents applicables.</>],
  ['6. Projets, biens et paiements', <>Les informations relatives aux terrains, appartements, villas, constructions ou programmes sont susceptibles d’évoluer et doivent être confirmées par CPI. Aucun paiement ne doit être effectué sur la base d’un simple écran, message ou appel non vérifiable. Les prix, cautions, échéanciers, frais, modalités de remboursement et conditions de transfert sont ceux du contrat ou du document officiel remis par CPI. Les paiements échelonnés, lorsqu’ils sont proposés, ne valent pas à eux seuls transfert de propriété.</>],
  ['7. Diaspora et représentation', <>CPI peut accompagner les clients résidant à l’étranger dans la coordination à distance, les échanges avec les proches au Sénégal, les visites, les procurations et les paiements internationaux, sous réserve des contrôles d’identité, des règles applicables et des documents requis. Une procuration ou un mandat doit être valable et vérifiable ; la plateforme ne remplace pas les formalités notariales, administratives ou bancaires.</>],
  ['8. Données personnelles et confidentialité', <>CPI traite les données nécessaires à la création du compte, à l’instruction et au suivi du dossier, à la sécurité, à la relation client, à la prévention de la fraude et au respect de ses obligations. Les données peuvent être consultées par les personnes CPI habilitées et, lorsque nécessaire, par des prestataires ou partenaires participant au traitement du dossier, dans la limite de leurs missions. CPI applique des mesures de contrôle d’accès, de traçabilité et de sécurité adaptées.</>],
  ['9. Vos droits', <>Conformément à la réglementation sénégalaise applicable à la protection des données personnelles, l’utilisateur peut demander l’accès, la rectification, la mise à jour ou la suppression de ses données, ainsi que s’opposer à certains traitements pour motif légitime, sous réserve des obligations légales et contractuelles de conservation. La demande doit être adressée à <a href="mailto:contact@cpi.sn">contact@cpi.sn</a>, avec les éléments permettant de vérifier l’identité du demandeur.</>],
  ['10. Sécurité et disponibilité', <>CPI met en œuvre des mesures raisonnables pour protéger la plateforme et les dossiers. L’utilisateur s’interdit toute tentative d’intrusion, extraction automatisée, transmission de code malveillant, contournement d’autorisation ou utilisation qui perturberait le service. La plateforme peut être interrompue temporairement pour maintenance, sécurité, évolution technique ou force majeure.</>],
  ['11. Propriété intellectuelle', <>La marque CPI, les logos, textes, interfaces, bases de données, éléments graphiques et logiciels de la plateforme sont protégés. Ils ne peuvent être copiés, revendus, adaptés ou exploités sans autorisation écrite. L’utilisateur conserve ses droits sur les documents qu’il transmet et autorise CPI à les utiliser uniquement pour les finalités nécessaires à son dossier, à ses services et à ses obligations.</>],
  ['12. Suspension et clôture', <>CPI peut limiter, suspendre ou clôturer un compte en cas de données fausses, fraude présumée, document irrégulier, usage abusif, impayé, atteinte à la sécurité ou violation des présentes conditions. Lorsque cela est possible, CPI informe l’utilisateur du motif et lui permet de régulariser. La clôture d’un compte ne supprime pas les données que CPI doit conserver pour une obligation légale, la preuve d’un contrat ou la défense de ses droits.</>],
  ['13. Responsabilité', <>CPI est responsable des obligations qui lui incombent au titre des contrats effectivement conclus. Elle ne garantit pas la disponibilité permanente du réseau, des services de tiers, des banques, des opérateurs de paiement ou des informations fournies par l’utilisateur. Aucune disposition ne limite une responsabilité qui ne peut légalement être exclue. Les conditions particulières d’un contrat signé prévalent sur les présentes en cas de contradiction.</>],
  ['14. Réclamations et règlement des différends', <>Toute question ou réclamation doit d’abord être adressée au service CPI à <a href="mailto:contact@cpi.sn">contact@cpi.sn</a> ou aux coordonnées publiées sur cpi.sn. CPI et l’utilisateur recherchent de bonne foi une solution amiable. Les présentes sont soumises au droit sénégalais, sous réserve des règles impératives applicables. À défaut d’accord amiable, les juridictions sénégalaises compétentes pourront être saisies.</>],
  ['15. Modification des conditions', <>CPI peut modifier les présentes pour tenir compte d’une évolution du service, de la réglementation ou de la sécurité. La version applicable est celle affichée au moment de l’utilisation. En cas de modification substantielle, CPI en informe les utilisateurs par un moyen approprié et peut demander une nouvelle acceptation.</>],
  ['16. Contact et version', <>Compagnie Prestige Immobilier (CPI SARL)<br />Ngor, Lot N°8, Almadies, Dakar, Sénégal<br /><a href="mailto:contact@cpi.sn">contact@cpi.sn</a> · +221 77 664 94 00 / +221 76 620 06 24<br /><br />Version de travail : 12 août 2026. Ce document doit être relu et validé par le conseil juridique de CPI avant mise en production comme condition contractuelle définitive.</>],
] as const;

export function ConditionsModal({ onClose }: { onClose: () => void }) {
  return <div role="presentation" onMouseDown={e => { if (e.target === e.currentTarget) onClose(); }} style={{ position: 'fixed', inset: 0, zIndex: 1000, display: 'grid', placeItems: 'center', padding: 16, background: 'rgba(28,8,16,.68)', backdropFilter: 'blur(5px)' }}>
    <section role="dialog" aria-modal="true" aria-labelledby="terms-title" style={{ width: 'min(900px, 100%)', maxHeight: 'min(92vh, 900px)', overflowY: 'auto', background: 'var(--card)', border: '1px solid var(--border)', borderRadius: 'var(--r-md)', boxShadow: '0 24px 80px rgba(0,0,0,.28)', padding: 'clamp(22px, 4vw, 46px)' }}>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 20, marginBottom: 26 }}>
        <div><div style={{ color: 'var(--accent)', fontSize: '.75rem', fontWeight: 800, letterSpacing: '.05em', textTransform: 'uppercase' }}>Document contractuel</div><h1 id="terms-title" style={{ margin: '8px 0 8px', fontFamily: 'var(--font-display)', fontSize: 'clamp(1.7rem, 4vw, 2.6rem)' }}>Conditions générales d’utilisation</h1><p style={{ margin: 0, color: 'var(--muted-foreground)', lineHeight: 1.6 }}>MONESPACE.CPI · Version de travail du 12 août 2026</p></div>
        <button type="button" aria-label="Fermer les conditions d’utilisation" onClick={onClose} style={{ flexShrink: 0, border: '1px solid var(--border)', borderRadius: '50%', width: 38, height: 38, background: 'var(--card)', color: 'var(--foreground)', cursor: 'pointer', fontSize: 22, lineHeight: 1 }}>×</button>
      </div>
      <div style={{ padding: 14, marginBottom: 24, borderRadius: 'var(--r-sm)', background: 'rgba(200,146,26,.10)', color: 'var(--foreground)', fontSize: '.875rem', lineHeight: 1.6 }}><strong>À retenir :</strong> l’inscription crée un compte de suivi. Elle ne constitue pas une promesse de prêt, une décision bancaire, une réservation ou un transfert de propriété. Les contrats particuliers signés avec CPI prévalent pour chaque opération.</div>
      {sections.map(([title, content]) => <section key={title} style={{ padding: '20px 0', borderTop: '1px solid var(--border)' }}><h2 style={{ margin: '0 0 9px', fontFamily: 'var(--font-display)', fontSize: '1.08rem' }}>{title}</h2><p style={{ margin: 0, color: 'var(--muted-foreground)', lineHeight: 1.75, fontSize: '.92rem' }}>{content}</p></section>)}
      <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 10, paddingTop: 22, borderTop: '1px solid var(--border)' }}><button type="button" onClick={onClose} style={{ padding: '12px 18px', border: 0, borderRadius: 'var(--r-sm)', background: 'var(--primary)', color: 'var(--primary-foreground)', cursor: 'pointer', fontWeight: 700 }}>Retour à l’inscription</button></div>
    </section>
  </div>;
}

export default function ConditionsPage({ onNavigate }: { onNavigate: (page: AppPage) => void }) {
  return <main style={{ minHeight: '100vh', background: 'var(--background)', color: 'var(--foreground)' }}>
    <header style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 16, padding: '20px clamp(20px, 5vw, 64px)', borderBottom: '1px solid var(--border)', background: 'var(--card)' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
        <img src={cpiLogo} alt="CPI" style={{ width: 48, height: 48, objectFit: 'cover', borderRadius: '50%', clipPath: 'circle(50%)' }} />
        <div><strong style={{ display: 'block', fontFamily: 'var(--font-display)' }}>MONESPACE.CPI</strong><span style={{ color: 'var(--muted-foreground)', fontSize: '.75rem' }}>Conditions générales d’utilisation</span></div>
      </div>
      <button type="button" onClick={() => onNavigate('register')} style={{ display: 'inline-flex', alignItems: 'center', gap: 7, padding: '10px 14px', border: '1px solid var(--border)', borderRadius: 'var(--r-sm)', background: 'var(--card)', color: 'var(--foreground)', cursor: 'pointer', fontWeight: 700 }}><ArrowLeft size={16} /> Retour</button>
    </header>
    <div style={{ maxWidth: 820, margin: '0 auto', padding: 'clamp(28px, 6vw, 72px) 20px 80px' }}>
      <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '8px 12px', borderRadius: 999, background: 'rgba(200,146,26,.10)', color: 'var(--accent)', fontSize: '.75rem', fontWeight: 700 }}><FileText size={15} /> Document à valider par le conseil juridique</div>
      <h1 style={{ margin: '18px 0 10px', fontFamily: 'var(--font-display)', fontSize: 'clamp(2rem, 5vw, 3.4rem)', lineHeight: 1.05 }}>Conditions générales d’utilisation</h1>
      <p style={{ maxWidth: 680, color: 'var(--muted-foreground)', fontSize: '1rem', lineHeight: 1.7 }}>Les règles qui encadrent l’accès à MONESPACE.CPI, le suivi de votre projet immobilier et la protection des informations confiées à CPI.</p>
      <div style={{ display: 'flex', gap: 10, alignItems: 'flex-start', padding: 16, margin: '28px 0 34px', border: '1px solid rgba(26,107,68,.18)', background: 'rgba(26,107,68,.06)', borderRadius: 'var(--r-md)', color: 'var(--foreground)', fontSize: '.875rem', lineHeight: 1.6 }}><ShieldCheck size={20} style={{ color: 'var(--success)', flexShrink: 0 }} /><span>La plateforme sert à faciliter l’accompagnement et le suivi. Une simulation ou un dossier en ligne ne remplace pas un contrat signé et ne constitue pas une garantie de financement.</span></div>
      {sections.map(([title, content]) => <section key={title} style={{ padding: '22px 0', borderTop: '1px solid var(--border)' }}><h2 style={{ margin: '0 0 9px', fontFamily: 'var(--font-display)', fontSize: '1.15rem' }}>{title}</h2><p style={{ margin: 0, color: 'var(--muted-foreground)', lineHeight: 1.75, fontSize: '.93rem' }}>{content}</p></section>)}
      <button type="button" onClick={() => onNavigate('register')} style={{ display: 'inline-flex', alignItems: 'center', gap: 8, marginTop: 20, padding: '13px 18px', border: 0, borderRadius: 'var(--r-sm)', background: 'var(--primary)', color: 'var(--primary-foreground)', cursor: 'pointer', fontWeight: 700 }}><CheckCircle2 size={17} /> Retour à l’inscription</button>
    </div>
  </main>;
}
