import { ArrowLeft, CheckCircle2, FileText, ShieldCheck } from 'lucide-react';
import cpiLogo from '../../assets/image.png';
import type { AppPage } from '../App';
import { Modal } from './ui/overlays';

export const sections = [
  ['1. Objet et identité de CPI', <>Les présentes conditions régissent l’utilisation de MONESPACE.CPI, l’espace numérique de la Compagnie Prestige Immobilier (CPI SARL), société immobilière sénégalaise créée en 2003. La plateforme permet notamment de créer un compte, de renseigner un projet immobilier, de transmettre des informations et pièces justificatives, de suivre l’avancement d’un dossier et d’échanger avec les équipes CPI et, lorsque cela est nécessaire, ses partenaires autorisés.</>],
  ['2. Acceptation et capacité', <>La création d’un compte et l’utilisation de la plateforme impliquent l’acceptation des présentes conditions. L’utilisateur déclare être majeur et juridiquement capable de s’engager, ou agir avec l’autorisation de son représentant légal. Si une personne agit au nom d’une société ou d’un autre bénéficiaire, elle garantit disposer des pouvoirs nécessaires.</>],
  ['3. Compte utilisateur', <>L’utilisateur fournit des informations exactes, complètes et à jour. Il protège son mot de passe, ne partage pas son jeton ou ses identifiants et informe CPI sans délai de toute utilisation non autorisée. Un compte est personnel : il ne doit pas être créé pour usurper l’identité d’un tiers, contourner une mesure de sécurité ou créer des dossiers fictifs.</>],
  ['4. Dossier immobilier et informations transmises', <>Les informations saisies, notamment l’identité, le téléphone, la situation professionnelle, les revenus, le projet et les pièces justificatives, doivent être sincères et lisibles. L’utilisateur garantit disposer du droit de transmettre les documents déposés. Toute falsification, omission volontaire ou utilisation de documents appartenant à un tiers peut entraîner le refus ou la suspension du dossier et, le cas échéant, un signalement aux autorités compétentes.</>],
  ['5. Accompagnement, simulation et financement', <>Les simulations, estimations, orientations et messages affichés dans la plateforme sont fournis à titre indicatif, sauf contrat distinct signé par les parties. Ils ne constituent ni une promesse de prêt, ni une décision bancaire, ni une garantie d’acceptation, de taux, de montant, de délai ou de décaissement. Toute offre de financement, vente, réservation, construction, intermédiation ou prestation juridique est soumise à ses propres conditions, à la vérification du dossier et à la signature des documents applicables.</>],
  ['6. Projets, biens et paiements', <>Les informations relatives aux terrains, appartements, villas, constructions ou programmes sont susceptibles d’évoluer et doivent être confirmées par CPI. Aucun paiement ne doit être effectué sur la base d’un simple écran, message ou appel non vérifiable. Les prix, cautions, échéanciers, frais, modalités de remboursement et conditions de transfert sont ceux du contrat ou du document officiel remis par CPI. Les paiements échelonnés, lorsqu’ils sont proposés, ne valent pas à eux seuls transfert de propriété.</>],
  ['7. Diaspora et représentation', <>CPI peut accompagner les clients résidant à l’étranger dans la coordination à distance, les échanges avec les proches au Sénégal, les visites, les procurations et les paiements internationaux, sous réserve des contrôles d’identité, des règles applicables et des documents requis. Une procuration ou un mandat doit être valable et vérifiable ; la plateforme ne remplace pas les formalités notariales, administratives ou bancaires.</>],
  ['8. Données personnelles et confidentialité', <>CPI traite les données nécessaires à la création du compte, à l’instruction et au suivi du dossier, à la sécurité, à la relation client, à la prévention de la fraude et au respect de ses obligations. Les données peuvent être consultées par les personnes CPI habilitées et, lorsque nécessaire, par des prestataires ou partenaires participant au traitement du dossier, dans la limite de leurs missions. CPI applique des mesures de contrôle d’accès, de traçabilité et de sécurité adaptées.</>],
  ['9. Vos droits', <>Conformément à la réglementation sénégalaise applicable à la protection des données personnelles, l’utilisateur peut demander l’accès, la rectification, la mise à jour ou la suppression de ses données, ainsi que s’opposer à certains traitements pour motif légitime, sous réserve des obligations légales et contractuelles de conservation. La demande doit être adressée à <a href="mailto:contact@cpi.sn">contact@cpi.sn</a>, avec les éléments permettant de vérifier l’identité du demandeur.</>],
  ['10. Sécurité et disponibilité', <>CPI met en œuvre des mesures raisonnables pour protéger la plateforme et les dossiers. L’utilisateur s’interdit toute tentative d’intrusion, extraction automatisée, transmission de code malveillant, contournement d’autorisation ou utilisation qui perturberait le service. La plateforme peut être interrompue temporairement pour maintenance, sécurité, évolution technique ou force majeure.</>],
  ['11. Propriété intellectuelle', <>La marque CPI, les logos, textes, interfaces, bases de données, éléments graphiques et logiciels de la plateforme sont protégés. Ils ne peuvent être copiés, revendus, adaptés ou exploités sans autorisation écrite. L’utilisateur conserve ses droits sur les documents qu’il transmet et autorise CPI à les utiliser uniquement pour les finalités nécessaires à son dossier, à ses services et à ses obligations.</>],
  ['12. Suspension et clôture', <>CPI peut limiter, suspendre ou clôturer un compte en cas de données fausses, fraude présumée, document irrégulier, usage abusif, impayé, atteinte à la sécurité ou violation des présentes conditions. Lorsque cela est possible, CPI informe l’utilisateur du motif et lui permet de régulariser. La clôture d’un compte ne supprime pas les données que CPI doit conserver pour une obligation légale, la preuve d’un contrat ou la défense de ses droits.</>],
  ['13. Responsabilité', <>CPI est responsable des obligations qui lui incombent au titre des contrats effectivement conclus. Elle ne garantit pas la disponibilité permanente du réseau, des services de tiers, des banques, des opérateurs de paiement ou des informations fournies par l’utilisateur. Aucune disposition ne limite une responsabilité qui ne peut légalement être exclue. Les conditions particulières d’un contrat signé prévalent sur les présentes en cas de contradiction.</>],
  ['14. Réclamations et règlement des différends', <>Toute question ou réclamation doit d’abord être adressée au service CPI à <a href="mailto:contact@cpi.sn">contact@cpi.sn</a> ou aux coordonnées publiées sur cpi.sn. CPI et l’utilisateur recherchent de bonne foi une solution amiable. Les présentes sont soumises au droit sénégalais, sous réserve des règles impératives applicables. À défaut d’accord amiable, les juridictions sénégalaises compétentes pourront être saisies.</>],
  ['15. Modification des conditions', <>CPI peut modifier les présentes pour tenir compte d’une évolution du service, de la réglementation ou de la sécurité. La version applicable est celle affichée au moment de l’utilisation. En cas de modification substantielle, CPI en informe les utilisateurs par un moyen approprié et peut demander une nouvelle acceptation.</>],
  ['16. Contact et version', <>Compagnie Prestige Immobilier (CPI SARL)<br />Ngor, Lot N°8, Almadies, Dakar, Sénégal<br /><a href="mailto:contact@cpi.sn">contact@cpi.sn</a> · +221 77 664 94 00 / +221 76 620 06 24<br /><br />Version 1.0 · Applicable à compter du 12 août 2026.</>],
  ['17. Définitions', <>Dans les présentes, « CPI » désigne la Compagnie Prestige Immobilier (CPI SARL) ; « plateforme » désigne MONESPACE.CPI, ses pages, espaces, formulaires, interfaces, API et services associés ; « utilisateur » désigne toute personne qui consulte ou utilise la plateforme ; « client » désigne l’utilisateur qui dispose d’un dossier immobilier ; « partenaire » désigne une banque, un assureur, un notaire, un cabinet, un prestataire technique ou tout autre intervenant autorisé ; « dossier » désigne l’ensemble des informations, pièces, échanges, décisions et documents relatifs à un projet.</>],
  ['18. Accès au service', <>La plateforme est accessible sous réserve d’une connexion internet, d’un navigateur compatible et du respect des présentes. Certaines fonctions sont réservées aux utilisateurs authentifiés ou à des rôles professionnels habilités. CPI peut faire évoluer les écrans, les parcours, les fonctionnalités et les conditions d’accès afin d’améliorer le service, de corriger une vulnérabilité, de respecter une obligation ou de maintenir la qualité du traitement.</>],
  ['19. Création et vérification du compte', <>Lors de l’inscription, l’utilisateur choisit un identifiant et un mot de passe conformes aux règles affichées. CPI peut demander une vérification de l’adresse e-mail, du numéro de téléphone ou de l’identité avant d’ouvrir une fonction sensible. Les contrôles peuvent inclure une pièce d’identité, un justificatif de domicile, un justificatif professionnel, un document de revenus ou toute pièce raisonnablement nécessaire à la compréhension du projet et à la prévention de la fraude.</>],
  ['20. Exactitude et mise à jour', <>L’utilisateur vérifie les données affichées avant de les confirmer et les met à jour lorsqu’elles changent. Une adresse e-mail, un téléphone, une situation professionnelle, un revenu ou une adresse erronés peuvent empêcher CPI de contacter l’utilisateur, retarder l’étude, produire une estimation inadaptée ou compromettre une formalité. CPI peut demander une nouvelle pièce lorsque le document est expiré, illisible, incohérent, incomplet ou incompatible avec les informations déclarées.</>],
  ['21. Dossier incomplet ou irrecevable', <>Un dossier peut être placé en attente, retourné pour correction, refusé ou clôturé lorsqu’il est incomplet, incohérent, hors périmètre, non finançable selon les critères applicables ou incompatible avec une obligation de conformité. Cette décision ne constitue pas une appréciation de la valeur personnelle de l’utilisateur. CPI peut expliquer les éléments manquants dans la limite de ses obligations de confidentialité, de ses procédures internes et des informations communiquées par ses partenaires.</>],
  ['22. Pièces justificatives et conservation', <>L’utilisateur téléverse des fichiers exempts de virus, lisibles et correspondant au dossier. Il ne transmet pas de document médical, bancaire ou d’identité d’un tiers sans base légale, mandat ou autorisation. Les documents peuvent être conservés pendant la durée utile à l’instruction, à l’exécution des contrats, à la preuve des opérations, à la lutte contre la fraude et aux obligations légales. À l’expiration de cette durée, ils sont supprimés, anonymisés ou archivés selon les règles applicables.</>],
  ['23. Notifications et communications', <>L’utilisateur accepte de recevoir les communications nécessaires au fonctionnement du compte et au suivi de son dossier par e-mail, téléphone, SMS, WhatsApp ou notification dans la plateforme, selon les coordonnées fournies et les fonctions disponibles. Les communications commerciales éventuelles font l’objet d’une base et d’un mécanisme de désinscription distincts. L’utilisateur reste responsable de la consultation de sa messagerie, de la protection de son téléphone et du signalement d’un changement de coordonnées.</>],
  ['24. Simulateur et résultats indicatifs', <>Tout simulateur utilise les hypothèses, données et paramètres indiqués au moment du calcul. Le résultat peut varier selon les revenus vérifiés, charges, garanties, durée, taux, assurance, frais, politique du partenaire et évolution du projet. Une mensualité estimée n’est pas une mensualité contractuelle ; un montant affiché n’est pas un engagement de décaissement. L’utilisateur doit demander une proposition écrite et vérifier les conditions avant toute décision financière.</>],
  ['25. Rôle de CPI dans le financement', <>Lorsque CPI facilite une demande de financement, elle peut collecter les informations, préparer un dossier, coordonner des échanges, présenter des options ou suivre les étapes communiquées par un partenaire. CPI ne se substitue pas à la banque ou à l’organisme qui prend la décision de crédit, ne garantit pas l’obtention d’un financement et ne peut pas modifier unilatéralement les critères, délais, taux, garanties ou décisions d’un partenaire.</>],
  ['26. Partenaires et services tiers', <>Certains services peuvent dépendre d’un partenaire : banque, opérateur de paiement, service d’identification, fournisseur de stockage, outil de communication, cabinet juridique, notaire ou professionnel de l’immobilier. Les conditions de ce tiers peuvent s’appliquer en complément. CPI sélectionne et encadre ses intervenants dans la mesure nécessaire, mais ne contrôle pas les décisions, contenus, délais ou interruptions qui relèvent exclusivement d’un tiers.</>],
  ['27. Biens immobiliers et informations foncières', <>Les descriptions, superficies, localisations, statuts, documents fonciers, visuels, disponibilités et prix publiés ou communiqués doivent être confirmés par les documents officiels de l’opération. Une présentation commerciale ne remplace pas une vérification foncière, administrative, urbanistique, notariale ou technique. L’utilisateur doit obtenir les documents pertinents, poser ses questions et, lorsque nécessaire, se faire assister par un professionnel indépendant avant de signer ou payer.</>],
  ['28. Réservation, vente et construction', <>La réservation d’un bien, la vente d’un terrain, la construction d’une villa ou d’un immeuble, la location et toute prestation d’accompagnement sont régies par un document particulier : contrat, bon de réservation, compromis, acte, devis, marché de travaux, mandat ou convention. Ce document fixe notamment le bien, le prix, les délais, les obligations, les conditions suspensives, les pénalités, les modalités de paiement, la remise des documents et les règles de résiliation.</>],
  ['29. Paiements, reçus et lutte contre la fraude', <>Tout paiement doit être effectué exclusivement selon les coordonnées et instructions figurant sur un document officiel de CPI ou d’un prestataire autorisé. CPI ne demande jamais à l’utilisateur de communiquer son mot de passe, son code de validation, son numéro complet de carte ou son jeton de session. L’utilisateur vérifie le bénéficiaire, conserve le reçu et signale immédiatement une demande inhabituelle. Un écran de la plateforme ne vaut pas reçu si aucun justificatif officiel n’est délivré.</>],
  ['30. Paiement échelonné et impayé', <>Lorsqu’un échéancier est prévu par contrat, les dates, montants et conséquences d’un retard sont ceux de ce contrat. Un retard peut entraîner une relance, la suspension d’une étape, des frais prévus, une renégociation ou la résiliation selon les stipulations applicables. La plateforme peut afficher un suivi administratif, mais ne modifie pas le contrat. Toute difficulté doit être signalée rapidement afin qu’une solution puisse être examinée avant l’échéance.</>],
  ['31. Utilisation loyale et interdictions', <>Il est interdit de contourner une limitation, d’accéder au compte d’autrui, d’extraire des données, de sonder les serveurs, d’introduire un code malveillant, de surcharger le service, de copier l’interface, de diffuser des documents confidentiels, d’utiliser une identité fictive, de transmettre des informations frauduleuses ou de se servir de la plateforme pour une activité illégale, abusive, discriminatoire, trompeuse ou contraire aux droits d’un tiers.</>],
  ['32. Preuve et journalisation', <>Les journaux techniques, historiques de connexion, traces d’accès, horodatages, confirmations, échanges et enregistrements de sécurité peuvent être conservés et utilisés comme éléments de preuve, sous réserve des règles applicables. Les données informatiques produites par la plateforme sont présumées fiables jusqu’à preuve contraire lorsque les conditions de conservation et d’intégrité sont réunies. L’utilisateur doit conserver les contrats, reçus et confirmations qui lui sont remis.</>],
  ['33. Confidentialité des échanges', <>Les échanges avec CPI peuvent contenir des informations personnelles, financières, foncières ou commerciales. L’utilisateur ne doit pas transférer à un tiers un lien signé, un document confidentiel ou une capture contenant les données d’une autre personne. CPI limite l’accès interne selon les besoins du dossier. La confidentialité ne s’applique pas aux informations déjà publiques, légalement demandées par une autorité ou nécessaires à l’exécution d’un contrat et à la défense des droits.</>],
  ['34. Données de contact et prospection', <>Les coordonnées utilisées pour le suivi opérationnel peuvent être utilisées afin de répondre à une demande, informer d’une étape, demander une pièce, prévenir d’un incident ou exécuter un contrat. Les messages promotionnels sont séparés du suivi nécessaire et peuvent être refusés. Le refus de prospection ne bloque pas les communications indispensables au compte ou au dossier. Les préférences peuvent être modifiées par le lien prévu dans le message ou en écrivant à CPI.</>],
  ['35. Sécurité des accès', <>L’utilisateur ferme sa session sur un appareil partagé, utilise un mot de passe unique, maintient son appareil à jour et n’installe pas d’extension douteuse. Il prévient CPI en cas de perte de téléphone, de compromission d’e-mail, de message suspect ou de connexion inconnue. CPI peut révoquer un jeton, imposer une nouvelle authentification, suspendre une opération ou demander une vérification supplémentaire lorsqu’un risque est détecté.</>],
  ['36. Disponibilité, maintenance et force majeure', <>CPI cherche à maintenir le service mais ne promet ni une disponibilité continue ni l’absence d’erreur. Des interruptions peuvent résulter d’une maintenance, d’une panne d’hébergement, d’un incident réseau, d’une indisponibilité d’un partenaire, d’une cyberattaque, d’une décision administrative, d’un conflit, d’une catastrophe, d’une coupure d’énergie ou de tout événement échappant raisonnablement au contrôle de CPI. Les obligations contractuelles déjà échues restent régies par leur contrat.</>],
  ['37. Propriété intellectuelle et licences', <>CPI ou ses concédants détiennent les droits sur les marques, logos, noms de domaine, textes, photographies, plans, vidéos, logiciels, bases de données, modèles et éléments graphiques de MONESPACE.CPI. Une licence personnelle, limitée, non exclusive et non transférable est accordée pour utiliser le service conformément aux présentes. Toute reproduction, extraction, représentation, adaptation, ingénierie inverse ou exploitation commerciale non autorisée est interdite.</>],
  ['38. Contenus transmis par l’utilisateur', <>L’utilisateur autorise CPI, pendant la durée nécessaire, à héberger, reproduire, consulter et transmettre les contenus qu’il dépose uniquement pour fournir le service, instruire le dossier, réaliser les contrôles, répondre à ses demandes, respecter une obligation et défendre ses droits. Il garantit que ces contenus ne violent aucun droit et qu’ils peuvent être traités pour ces finalités. CPI ne revend pas les documents personnels déposés dans un dossier.</>],
  ['39. Liens et contenus externes', <>La plateforme peut contenir des liens vers cpi.sn, des partenaires, des banques, des services publics ou d’autres sites. Ces liens sont fournis pour faciliter le parcours et ne signifient pas que CPI garantit le contenu, la disponibilité ou la sécurité du site tiers. L’utilisateur prend connaissance des conditions et politiques du tiers avant de lui transmettre des données ou d’effectuer une opération.</>],
  ['40. Réclamations et médiation amiable', <>Une réclamation précise est adressée à CPI avec le nom du titulaire, la référence du dossier, la date des faits, l’objet de la demande et les pièces utiles. CPI accuse réception lorsque cela est possible et examine la demande avec les services concernés. Les échanges amiables ne privent aucune partie d’un droit ou d’un recours. Les délais et procédures propres à un contrat particulier peuvent s’appliquer en priorité.</>],
  ['41. Suspension, résiliation et effets', <>L’utilisateur peut cesser d’utiliser la plateforme et demander la clôture de son compte, sans préjudice des contrats, paiements, obligations de confidentialité, règles de preuve et obligations légales qui continuent de produire leurs effets. CPI peut suspendre immédiatement un accès lorsqu’une mesure est nécessaire à la sécurité ou à la protection des personnes. La suspension ne constitue pas automatiquement une résiliation d’un contrat immobilier ou financier.</>],
  ['42. Responsabilité et limites', <>CPI répond des dommages directs dont elle est légalement responsable. Dans la mesure permise par la loi, CPI ne répond pas des pertes indirectes, manque à gagner, perte d’opportunité, interruption imputable à un tiers, défaut d’information fourni par l’utilisateur ou décision indépendante d’un partenaire. Cette clause ne limite pas les obligations impératives, la responsabilité résultant d’une faute qui ne peut être exclue, ni les droits reconnus au consommateur par la réglementation applicable.</>],
  ['43. Indépendance des clauses', <>Si une stipulation est déclarée nulle, illégale ou inapplicable, les autres stipulations restent en vigueur. Les parties s’efforcent de remplacer la stipulation concernée par une disposition valable qui se rapproche le plus possible de son objectif économique et juridique. Le fait pour CPI de ne pas exercer immédiatement un droit ne vaut pas renonciation à ce droit.</>],
  ['44. Droit applicable et juridiction', <>Les présentes sont régies par le droit sénégalais. Les parties privilégient une résolution amiable. À défaut d’accord, le litige est soumis aux juridictions sénégalaises compétentes, sous réserve des règles impératives de compétence et de protection applicables à la situation de l’utilisateur. Les contrats particuliers peuvent prévoir des modalités complémentaires, sans retirer à l’utilisateur les droits auxquels il ne peut renoncer.</>],
  ['45. Modification et version opposable', <>CPI peut mettre à jour les présentes pour refléter une évolution du service, de l’organisation ou du droit. La version affichée au moment de l’acceptation est conservée avec sa date et son numéro de version. Une modification importante peut nécessiter une nouvelle acceptation avant la poursuite de certaines fonctions. L’utilisateur est invité à consulter régulièrement les présentes et à conserver une copie des documents qui lui sont remis.</>],
] as const;

export function ConditionsModal({ onClose }: { onClose: () => void }) {
  // Radix apporte le piège de focus et la fermeture par Échap, qui manquaient.
  // Les classes `cpi-terms-modal` / `cpi-terms-dialog` sont conservées : la
  // mise en page mobile de globals.css les cible nommément.
  return <Modal
    open
    onClose={onClose}
    titre="Conditions générales d’utilisation"
    description="Version 1.0 · Applicable à compter du 12 août 2026"
    sansCroix
    largeur="min(1080px, 100%)"
    zIndex={1000}
    voile="rgba(28,8,16,.72)"
    classNameVoile="cpi-terms-modal"
    styleVoile={{ display: 'grid', placeItems: 'center', backdropFilter: 'blur(6px)' }}
    className="cpi-terms-dialog"
    style={{ maxHeight: 'min(94vh, 940px)', border: '1px solid rgba(255,255,255,.5)', borderRadius: 18, boxShadow: '0 28px 100px rgba(28,8,16,.35)', overflowX: 'hidden', padding: 0 }}
  >
    <>
      <header style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 20, padding: 'clamp(24px, 4vw, 42px)', background: 'var(--sidebar)', color: 'white' }}>
        <div><div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, color: '#F1CC76', fontSize: '.72rem', fontWeight: 800, letterSpacing: '.08em', textTransform: 'uppercase' }}>MONESPACE.CPI · CPI SARL</div><h1 id="terms-title" style={{ margin: '10px 0 8px', fontFamily: 'var(--font-display)', fontSize: 'clamp(1.8rem, 4vw, 2.8rem)', lineHeight: 1.05 }}>Conditions générales d’utilisation</h1><p style={{ margin: 0, color: 'rgba(255,255,255,.68)', lineHeight: 1.6 }}>Version 1.0 · Applicable à compter du 12 août 2026</p></div>
        <button type="button" aria-label="Fermer les conditions générales d’utilisation" onClick={onClose} style={{ flexShrink: 0, border: '1px solid rgba(255,255,255,.35)', borderRadius: '50%', width: 40, height: 40, background: 'rgba(255,255,255,.08)', color: 'white', cursor: 'pointer', fontSize: 24, lineHeight: 1 }}>×</button>
      </header>
      <div style={{ padding: '0 clamp(22px, 5vw, 62px) 38px' }}>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, padding: '20px 0 6px' }} aria-label="Sommaire des conditions">
          {sections.slice(0, 8).map(([title]) => <span key={title} style={{ padding: '6px 10px', borderRadius: 999, background: 'var(--secondary)', color: 'var(--secondary-foreground)', fontSize: '.68rem', fontWeight: 700 }}>{title.replace(/^\d+\. /, '')}</span>)}
          <span style={{ padding: '6px 10px', borderRadius: 999, background: 'rgba(200,146,26,.12)', color: '#8A6300', fontSize: '.68rem', fontWeight: 700 }}>45 articles</span>
        </div>
        <div style={{ padding: 16, margin: '14px 0 8px', borderLeft: '3px solid var(--accent)', background: 'rgba(200,146,26,.08)', color: 'var(--foreground)', fontSize: '.875rem', lineHeight: 1.65 }}><strong>Champ d’application :</strong> ces conditions encadrent le compte, le dossier immobilier, les échanges et les services numériques de CPI. Les contrats particuliers signés pour une vente, une construction, une réservation ou un financement précisent les engagements propres à l’opération.</div>
        {sections.map(([title, content]) => <section key={title} style={{ padding: '24px 0', borderTop: '1px solid var(--border)' }}><h2 style={{ margin: '0 0 10px', fontFamily: 'var(--font-display)', fontSize: '1.12rem', color: 'var(--foreground)' }}>{title}</h2><p style={{ margin: 0, color: 'var(--muted-foreground)', lineHeight: 1.82, fontSize: '.92rem' }}>{content}</p></section>)}
        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 10, paddingTop: 24, borderTop: '1px solid var(--border)' }}><button type="button" onClick={onClose} style={{ padding: '13px 20px', border: 0, borderRadius: 'var(--r-sm)', background: 'var(--primary)', color: 'var(--primary-foreground)', cursor: 'pointer', fontWeight: 700 }}>Retour à l’inscription</button></div>
      </div>
    </>
  </Modal>;
}

export default function ConditionsPage({ onNavigate }: { onNavigate: (page: AppPage) => void }) {
  return <main style={{ minHeight: '100vh', background: 'var(--background)', color: 'var(--foreground)' }}>
    <header style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 16, padding: '20px clamp(20px, 5vw, 64px)', borderBottom: '1px solid var(--border)', background: 'var(--card)' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
        <img src={cpiLogo} alt="CPI" style={{ width: 48, height: 48, objectFit: 'cover', borderRadius: '50%', clipPath: 'circle(50%)' }} />
        <div><strong style={{ display: 'block', fontFamily: 'var(--font-display)' }}>MONESPACE.CPI</strong><span style={{ color: 'var(--muted-foreground)', fontSize: '.75rem' }}>Conditions générales d’utilisation</span></div>
      </div>
      <button type="button" onClick={() => onNavigate('register')} style={{ display: 'inline-flex', alignItems: 'center', gap: 7, padding: '10px 14px', border: '1px solid var(--border)', borderRadius: 'var(--r-sm)', background: 'var(--card)', color: 'var(--foreground)', cursor: 'pointer', fontWeight: 700 }}><ArrowLeft size={16} /> Retour</button>
    </header>
    <div style={{ maxWidth: 820, margin: '0 auto', padding: 'clamp(28px, 6vw, 72px) 20px 80px' }}>
      <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '8px 12px', borderRadius: 999, background: 'rgba(200,146,26,.10)', color: 'var(--accent-text)', fontSize: '.75rem', fontWeight: 700 }}><FileText size={15} /> Conditions générales · Version 1.0</div>
      <h1 style={{ margin: '18px 0 10px', fontFamily: 'var(--font-display)', fontSize: 'clamp(2rem, 5vw, 3.4rem)', lineHeight: 1.05 }}>Conditions générales d’utilisation</h1>
      <p style={{ maxWidth: 680, color: 'var(--muted-foreground)', fontSize: '1rem', lineHeight: 1.7 }}>Les règles qui encadrent l’accès à MONESPACE.CPI, le suivi de votre projet immobilier et la protection des informations confiées à CPI.</p>
      <div style={{ display: 'flex', gap: 10, alignItems: 'flex-start', padding: 16, margin: '28px 0 34px', border: '1px solid rgba(26,107,68,.18)', background: 'rgba(26,107,68,.06)', borderRadius: 'var(--r-md)', color: 'var(--foreground)', fontSize: '.875rem', lineHeight: 1.6 }}><ShieldCheck size={20} style={{ color: 'var(--success)', flexShrink: 0 }} /><span>La plateforme sert à faciliter l’accompagnement et le suivi. Une simulation ou un dossier en ligne ne remplace pas un contrat signé et ne constitue pas une garantie de financement.</span></div>
      {sections.map(([title, content]) => <section key={title} style={{ padding: '22px 0', borderTop: '1px solid var(--border)' }}><h2 style={{ margin: '0 0 9px', fontFamily: 'var(--font-display)', fontSize: '1.15rem' }}>{title}</h2><p style={{ margin: 0, color: 'var(--muted-foreground)', lineHeight: 1.75, fontSize: '.93rem' }}>{content}</p></section>)}
      <button type="button" onClick={() => onNavigate('register')} style={{ display: 'inline-flex', alignItems: 'center', gap: 8, marginTop: 20, padding: '13px 18px', border: 0, borderRadius: 'var(--r-sm)', background: 'var(--primary)', color: 'var(--primary-foreground)', cursor: 'pointer', fontWeight: 700 }}><CheckCircle2 size={17} /> Retour à l’inscription</button>
    </div>
  </main>;
}
